### ISSUE TITLE
Cannot Find Library -lvl

### ISSUE THREAD

**Issue by michaelholm-ce** [tolga-b/BINGpp#1]
Hello,

I am on 64-bit linux (Ubuntu 14.04).  When I compile the project, I get the following error about not finding the vlfeat library:

```
Linking CXX executable BING++
/usr/bin/ld: cannot find -lvl
collect2: error: ld returned 1 exit status
make[2]: *** [Objectness/BING++] Error 1
make[1]: *** [Objectness/CMakeFiles/BING++.dir/all] Error 2
make: *** [all] Error 2
```

Any help is appreciated,

Michael

**Comment by tolga-b** [comment]
Hello Michael,
My bad, I now uploaded the required library to ext folder. If you pull the
repo again it should work.
I guess most people have vlfeat library somewhere in path and did not
realize this before, so thank you for reporting it!

Best

On Wed, Mar 2, 2016 at 4:07 PM, Michael Holm notifications@github.com
wrote:

> Hello,
> 
> I am on 64-bit linux (Ubuntu 14.04). When I compile the project, I get the
> following error about not finding the vlfeat library:
> 
> Linking CXX executable BING++
> /usr/bin/ld: cannot find -lvl
> collect2: error: ld returned 1 exit status
> make[2]: **\* [Objectness/BING++] Error 1
> make[1]: **\* [Objectness/CMakeFiles/BING++.dir/all] Error 2
> make: **\* [all] Error 2
> 
> Any help is appreciated,
> 
> Michael
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tolga-b/BINGpp/issues/1.

## 

Tolga

**Comment by michaelholm-ce** [comment]
Thanks for your quick response and update. 

The 'make' command is now reporting this error:

```
/usr/bin/ld: CMakeFiles/BING++.dir/Objectness.cpp.o: undefined reference to symbol '_ZN2cv9normalizeERKNS_11_InputArrayERKNS_17_InputOutputArrayEddiiS2_'
```

Any ideas on this?  I'm not sure if this part is an issue or a question.  I'll post the full make output below.  It looks like it _may_ have to do with different versions of opencv.

Thanks,

Michael

```
exx@ubuntu:~/BINGpp/src/build$ sudo make
Scanning dependencies of target blas
[  4%] Building C object LibLinear/CMakeFiles/blas.dir/blas/daxpy.c.o
[  8%] Building C object LibLinear/CMakeFiles/blas.dir/blas/ddot.c.o
[ 12%] Building C object LibLinear/CMakeFiles/blas.dir/blas/dnrm2.c.o
[ 16%] Building C object LibLinear/CMakeFiles/blas.dir/blas/dscal.c.o
Linking C static library libblas.a
[ 16%] Built target blas
Scanning dependencies of target liblinear
[ 20%] Building CXX object LibLinear/CMakeFiles/liblinear.dir/linear.cpp.o
[ 24%] Building CXX object LibLinear/CMakeFiles/liblinear.dir/tron.cpp.o
Linking CXX static library libliblinear.a
[ 24%] Built target liblinear
[ 28%] Building NVCC (Device) object Objectness/CMakeFiles/gSLIC_lib.dir/gSLIC_Lib/engines/./gSLIC_lib_generated_gSLIC_seg_engine_GPU.cu.o
/home/exx/BINGpp/src/Objectness/gSLIC_Lib/engines/gSLIC_seg_engine_GPU.cu(227): warning: __shared__ memory variable with non-empty constructor or destructor (potential race between threads)

/home/exx/BINGpp/src/Objectness/gSLIC_Lib/engines/gSLIC_seg_engine_GPU.cu(228): warning: __shared__ memory variable with non-empty constructor or destructor (potential race between threads)

cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
Scanning dependencies of target gSLIC_lib
[ 32%] Building CXX object Objectness/CMakeFiles/gSLIC_lib.dir/gSLIC_Lib/engines/gSLIC_core_engine.cpp.o
/home/exx/BINGpp/src/Objectness/gSLIC_Lib/engines/gSLIC_core_engine.cpp:1:9: warning: #pragma once in main file [enabled by default]
 #pragma once
         ^
[ 36%] Building CXX object Objectness/CMakeFiles/gSLIC_lib.dir/gSLIC_Lib/engines/gSLIC_seg_engine.cpp.o
/home/exx/BINGpp/src/Objectness/gSLIC_Lib/engines/gSLIC_seg_engine.cpp:1:9: warning: #pragma once in main file [enabled by default]
 #pragma once
         ^
Linking CXX static library libgSLIC_lib.a
[ 36%] Built target gSLIC_lib
[ 40%] Building NVCC (Device) object Objectness/CMakeFiles/BING++.dir//./BING++_generated_kernel.cu.o
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
/home/exx/BINGpp/src/Objectness/stdafx.h(106): warning: integer conversion resulted in a change of sign

Scanning dependencies of target BING++
[ 44%] Building CXX object Objectness/CMakeFiles/BING++.dir/CmFile.cpp.o
[ 48%] Building CXX object Objectness/CMakeFiles/BING++.dir/CmShow.cpp.o
[ 52%] Building CXX object Objectness/CMakeFiles/BING++.dir/DataSetVOC.cpp.o
[ 56%] Building CXX object Objectness/CMakeFiles/BING++.dir/FilterBING.cpp.o
[ 60%] Building CXX object Objectness/CMakeFiles/BING++.dir/mtse.cpp.o
[ 64%] Building CXX object Objectness/CMakeFiles/BING++.dir/Objectness.cpp.o
/home/exx/BINGpp/src/Objectness/Objectness.cpp: In member function ‘void Objectness::evaluatePAMI12(CStr&)’:
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1484:68: warning: format ‘%g’ expects argument of type ‘float*’, but argument 7 has type ‘double*’ [-Wformat=]
    fscanf(f, "%d %d %d %d %g\n", &v[0], &v[1], &v[2], &v[3], &score);
                                                                    ^
/home/exx/BINGpp/src/Objectness/Objectness.cpp: In member function ‘void Objectness::evaluateECCV14(CStr&)’:
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1526:68: warning: format ‘%g’ expects argument of type ‘float*’, but argument 7 has type ‘double*’ [-Wformat=]
    fscanf(f, "%d %d %d %d %g\n", &v[0], &v[1], &v[2], &v[3], &score);
                                                                    ^
/home/exx/BINGpp/src/Objectness/Objectness.cpp: In static member function ‘static bool Objectness::matRead(const string&, cv::Mat&)’:
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1464:36: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  fread(headData, sizeof(int), 3, f);
                                    ^
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1466:49: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  fread(M.data, sizeof(char), M.step * M.rows, f);
                                                 ^
/home/exx/BINGpp/src/Objectness/Objectness.cpp: In member function ‘void Objectness::evaluatePAMI12(CStr&)’:
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1484:69: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(f, "%d %d %d %d %g\n", &v[0], &v[1], &v[2], &v[3], &score);
                                                                     ^
/home/exx/BINGpp/src/Objectness/Objectness.cpp: In member function ‘void Objectness::evaluateIJCV13(CStr&)’:
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1501:31: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(f, "%d\r\n", &numDet);
                               ^
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1505:60: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(f, "%d %d %d %d\r\n", &v[1], &v[0], &v[3], &v[2]);
                                                            ^
/home/exx/BINGpp/src/Objectness/Objectness.cpp: In member function ‘void Objectness::evaluateECCV14(CStr&)’:
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1522:29: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
   fscanf(f, "%d\n", &numDet);
                             ^
/home/exx/BINGpp/src/Objectness/Objectness.cpp:1526:69: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
    fscanf(f, "%d %d %d %d %g\n", &v[0], &v[1], &v[2], &v[3], &score);
                                                                     ^
[ 68%] Building CXX object Objectness/CMakeFiles/BING++.dir/stdafx.cpp.o
Linking CXX executable BING++
/usr/bin/ld: warning: libopencv_core.so.3.0, needed by //usr/local/lib/libopencv_imgcodecs.so, may conflict with libopencv_core.so.2.4
/usr/bin/ld: CMakeFiles/BING++.dir/Objectness.cpp.o: undefined reference to symbol '_ZN2cv9normalizeERKNS_11_InputArrayERKNS_17_InputOutputArrayEddiiS2_'
//usr/local/lib/libopencv_core.so.3.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Objectness/BING++] Error 1
make[1]: *** [Objectness/CMakeFiles/BING++.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tolga-b** [comment]
Are you using opencv 3.x or opencv 2.x? 
The code requires opencv 3.x right now.

**Comment by michaelholm-ce** [comment]
I'm using 2.4.8.  I'm afraid of breaking other things by switching, but I'll consider that.  You're welcome to separate the two parts of my issue, or remove the opencv part, if you like.  
Thanks,
Michael

**Comment by tolga-b** [comment]
I see, you actually do not need to change your opencv version on system level. It will work out if you download opencv 3, put it in any folder and then call cmake as:
cmake .. -DOPENCV_PATH=/path/to/opencv/ 

Best

**Comment by tharun2011** [comment]
Which glibc version is required? My current version is 2.12.
Having the following error:
`/usr/local/lib/libvl.so: undefined reference to 'memcpy@GLIBC_2.14'`

**Comment by tolga-b** [comment]
I see, vlfeat library that I included depends on a newer glibc version. I
believe Ubuntu 12.04 comes with glibc 2.15, and I tested the code on 14.04
which is 2.19.

You can try going to http://www.vlfeat.org/download.html and compiling
vlfeat for your system, or upgrading your operating system.

Best

On Thu, May 5, 2016 at 9:34 AM, tharun2011 notifications@github.com wrote:

> Which glibc version is required? My current version is 2.12.
> Having the following error:
> /usr/local/lib/libvl.so: undefined reference to 'memcpy@GLIBC_2.14'
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/tolga-b/BINGpp/issues/1#issuecomment-217155684

## 

Tolga

**Comment by tharun2011** [comment]
Having this error, when used run command
./src/Objectness/BING++ (absolute path to /datasets/VOC2007/)
`OpenCV Error: Assertion failed (ssize.area() > 0) in resize.`
Seems like this isn't loading the images.I have placed the images in VOC2007 directory.
And will the output be a text file consists of proposals?

**Comment by tolga-b** [comment]
Hello tharun2011,

That is interesting. The output will be in BING++_Results directory in
VOC2007.
Did you make sure the directory structure is the same as defined in VOC
readme?

Also VOC2007 directory contains:
/JPEGImages (this is where the images go)
/Annotations
/ImageSets
/SegmentationObject
/SegmentationClass

On Tue, May 17, 2016 at 5:53 AM, tharun2011 notifications@github.com
wrote:

> Having this error, when used run command
> ./src/Objectness/BING++ (absolute path to /datasets/VOC2007/)
> OpenCV Error: Assertion failed (ssize.area() > 0) in resize.
> Seems like this isn't loading the images.I have placed the images in
> VOC2007 directory.
> And will the output be a text file consists of proposals?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/tolga-b/BINGpp/issues/1#issuecomment-219671716

## 

Tolga

**Comment by tharun2011** [comment]
VOC2007 directory contains:
/Annotations
/JPEGImages 
/Results (contains ObjNessB2W8MAXBGR.idx,.wS1,.wS2 files)
/ImageSets
I have downloaded entire JPEGImages(~4952 images) directory. Output is generated as text files in Results directory.
How could I get proposals for the new images?
Update:
I have added new images to JPEGImages directory but it failed because the program is looking for Annotations files for these new images.
The file in Results directory consists of no.of proposals and then bounding boxes' coordinates.
`-20.5796, 189, 196, 301, 292`. What does the first number mean?

**Comment by tolga-b** [comment]
Right now running with another set of images require:
test.txt train.txt(dummy) val.txt(dummy) in ImageSets/Main/ that have image names.
YAML ground truth annotations for all images in Anootations/
It is not very clean at the moment, but I have plans of adding a cleaner interface time permitting.

The first number is confidence in the box. Also the boxes are ordered from the most likely to least likely. We found that using top 1000 boxes usually generate good results.
